version: '3.4'

services:
  demo:
    image: upadhyayshivam/demo-dotnet
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:80
    ports:
      - 80:80
    command: dotnet practices.dll
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - dev

  postgres_db:
    container_name: postgres_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=codinova1234
      - PGUSER=postgres
      - POSTGRES_DB=practice_db #optional (specify default database instead of $POSTGRES_DB)
    ports:
      - 5000:5432
    restart: always
    networks:
      - dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "practice_db"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s  
networks:
  dev:
    driver: bridge