version: '3.4'

services:
  demo:
    image: demo
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:80;https://+:443
        - ASPNETCORE_HTTPS_PORT=5254 
        - ASPNETCORE_Kestrel__Certificates__Default__Password=password
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - 5204:80
      - 5254:443
    command: dotnet practices.dll
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - dev

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=codinova1234
      - PGUSER=postgres
      - POSTGRES_DB=practice_db #optional (specify default database instead of $POSTGRES_DB)
    ports:
      - 5000:5432
    restart: always
    networks:
      - dev
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "practice_db"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s  
networks:
  dev:
    driver: bridge